const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

// public/codemirror-bundle.js is gitignored and generated by `bundle:codemirror`. A
// checkout that has never built it — a fresh clone, or a git worktree — loads the app
// with window.createPlanEditor undefined, so every file row renders but clicking one
// opens no editor. The two entry points meant to *start* the app therefore have to build
// it first. `electron` stays the deliberate raw launcher for a fast relaunch when the
// bundle is known to be current.
test('start and electron-dev build the CodeMirror bundle before launching', () => {
  for (const name of ['start', 'electron-dev']) {
    const cmd = pkg.scripts[name];
    assert.ok(cmd, `npm script "${name}" is missing`);
    assert.match(cmd, /electron \./, `npm script "${name}" no longer launches the app`);
    assert.match(cmd, /bundle:codemirror\s*&&/, `npm script "${name}" launches the app without building the CodeMirror bundle first`);
  }
});

test('the bundle script writes to the path index.html loads', () => {
  const outfile = /--outfile=(\S+)/.exec(pkg.scripts['bundle:codemirror']);
  assert.ok(outfile, 'bundle:codemirror has no --outfile');
  assert.equal(outfile[1], 'public/codemirror-bundle.js');

  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8');
  assert.match(html, /<script src="codemirror-bundle\.js">/);
});
